CREATE TABLE room
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          TEXT,
    restaurant_id BIGINT,
    CONSTRAINT pk_room PRIMARY KEY (id)
);

ALTER TABLE room
    ADD CONSTRAINT FK_ROOM_ON_RESTAURANT FOREIGN KEY (restaurant_id) REFERENCES restaurant (id);

ALTER TABLE tables
    ADD room_id BIGINT;

ALTER TABLE tables
    ADD CONSTRAINT FK_TABLE_ON_ROOM FOREIGN KEY (room_id) REFERENCES room (id);